### ISSUE TITLE
新入社員教育

### ISSUE THREAD

**Issue by JungSungHo** [JungSungHo/React-Tutorial#3]
## Task

- First Time[1:00:00]
  - [x] Reactの概要：https://github.com/JungSungHo/React-Tutorial/wiki/React-Concepts
    - [Reactの環境構築方法（公式ドキュメント）](https://ja.react.dev/blog/2023/03/16/introducing-react-dev)
  - [x] React project構成：https://github.com/JungSungHo/React-Tutorial/wiki/React-project-configuration
  - [x] components, modules, librariesとは：https://github.com/JungSungHo/React-Tutorial/wiki/What-are-components,-modules,-libraries%3F
  - [x] package.jsonとの比較：https://github.com/JungSungHo/React-Tutorial/wiki/Compare-with-package.json
  - [x] Reactの基礎知識 [17:48] https://www.youtube.com/watch?v=XKSYF2aZnkQ&list=PLX8Rsrpnn3IWPoM7-1YPDksRRkamRY25k
  - [x] JSXの記法 [15:45] https://www.youtube.com/watch?v=gLbTluYSb_U&list=PLX8Rsrpnn3IWPoM7-1YPDksRRkamRY25k&index=2

- Second Time[1:00:00]
  - [x] 環境設定（VSCode, NodeJs, Npm）：https://qiita.com/gumiTECH/items/4b82e4e3757f226df6b0
  - [x] Tutorial1：https://github.com/JungSungHo/React-Tutorial/pull/1
  - [x] Tutorial2：https://github.com/JungSungHo/React-Tutorial/pull/2

- Third Time[1:00:00]
  - [x] コンポーネントとprops [19:05] https://www.youtube.com/watch?v=Q-df0QgZuhE&list=PLX8Rsrpnn3IWPoM7-1YPDksRRkamRY25k&index=4
  - [x] コンポーネントのimportとexport [22:40] https://www.youtube.com/watch?v=Sex6Vc-NJEk&list=PLX8Rsrpnn3IWPoM7-1YPDksRRkamRY25k&index=5
  - [x] Q&A

- If possible
  - [ ] コンポーネントの状態管理 [21:27] https://www.youtube.com/watch?v=dTghhYtvPek&list=PLX8Rsrpnn3IWPoM7-1YPDksRRkamRY25k&index=6
  - [ ] 頻出するuseStateのケース3選 [18:06] https://www.youtube.com/watch?v=7MzVcLAtl8g&list=PLX8Rsrpnn3IWPoM7-1YPDksRRkamRY25k&index=7
  - [ ] Tutorial3：https://github.com/JungSungHo/React-Tutorial/pull/4
  - [ ] Tutorial4：https://github.com/JungSungHo/React-Tutorial/pull/5
  - [ ] TypeScript Sample：https://www.typescripttutorial.net/typescript-tutorial/typescript-hello-world/

※[MacにNode.jsをインストールする手順](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbEQtVWNZN1EzazhyOGhwQjJoTWpHQnIyRnNlQXxBQ3Jtc0trbVdMckM0bHE0UWY2SHpzMnpyOF84ekd6V0MxRGlRX1dfNTh1cl9TdFQwU3ZKRnRFVnczbVRiSXotakdzQ3RNelAyX2RIVHh4dTZ0LWphbE5ERmdUQUIzalhlRmt1TUFycEJjS2ZibTlGYmxaVGNoSQ&q=https%3A%2F%2Fqiita.com%2Fkyosuke5_20%2Fitems%2Fc5f68fc9d89b84c0df09&v=Ym4If5W9SS0)

**Comment by JungSungHo** [comment]
5/9 教育終了しましたので、クローズします。
